version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/rinsuki/socks2http
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: dep ensure
      - run: gox
      - run: ls -l
