version: 2
jobs:
  build:
    docker:
      - image: golang:1.11-stretch
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go build
      - run: ls -l
