name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          
      - name: Build for multiple platforms
        run: |
          mkdir -p dist/
          GOOS=darwin GOARCH=amd64 go build -o dist/socks2http_darwin_amd64
          GOOS=linux GOARCH=amd64 go build -o dist/socks2http_linux_amd64
          GOOS=windows GOARCH=amd64 go build -o dist/socks2http_windows_amd64.exe
          GOOS=linux GOARCH=arm go build -o dist/socks2http_linux_arm
          GOOS=linux GOARCH=arm64 go build -o dist/socks2http_linux_arm64
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*
